version: '3.9'

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - static_files:/app/static
      - media_files:/app/media
      - .:/app
    depends_on:
      - redis
      - celery
      - db


  celery:
    container_name: celery
    build: .
    command: celery -A derzanBot worker -l info
    restart: always
    env_file:
      - .env
    volumes:
      - static_files:/app/static
      - media_files:/app/media
      - .:/app
    depends_on:
      - redis
      - db


  flower:
    image: mher/flower
    restart: always
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery


  redis:
    image: redis:alpine3.17
    restart: always
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: 'derzan_db'
    restart: always
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    healthcheck:
      test: [ “CMD-SHELL”, “pg_isready” ]
      interval: 1m
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  static_files:
  media_files:
  postgres_data:

