version: '3.4'

services:
  derzanbot:
    image: derzanbot
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8000
    env_file:
      - .env

    volumes:
      - shared_data:/media
    depends_on:
      - redis
      - celery
  redis:
    container_name: redis
    image: redis:alpine3.17
  celery:
    container_name: celery
    build: .
    command: celery -A derzanBot worker -l info
    env_file:
      - .env
    volumes:
      - shared_data:/media
    depends_on:
      - redis
volumes:
  shared_data: