version: '3.7'

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - static_files:/app/static
      - media_files:/app/media
      - .:/app
    depends_on:
      - redis
      - celery


  celery:
    container_name: celery
    build: .
    command: celery -A derzanBot worker -l info
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - static_files:/app/static
      - media_files:/app/media
      - .:/app
    depends_on:
      - redis


  flower:
    image: mher/flower
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery


  redis:
    image: redis:alpine3.17
    restart: unless-stopped
    volumes:
      - .:/app


volumes:
  static_files:
  media_files:

