version: '3.7'

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - static_files:/app/static
      - media_files:/app/media
    depends_on:
      - redis
      - celery

  redis:
    restart: unless-stopped
    image: redis:alpine3.17

  celery:
    container_name: celery
    build: .
    command: celery -A derzanBot worker -l info
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - static_files:/app/static
      - media_files:/app/media
    depends_on:
      - redis

volumes:
  static_files:
  media_files:
